=== miroque/pp-model-concept-01/src/test/resources/personal-profile.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="personal-profile">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="identity">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="person">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="fio"/>
                    <xs:element type="xs:date" name="birth-date"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="account">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="login"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="data">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="knowledge" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element name="knowledge" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="name"/>
                        </xs:sequence>
                        <xs:attribute type="xs:byte" name="level" use="optional"/>
                        <xs:attribute type="xs:dateTime" name="recalculated" use="optional"/>
                        <xs:attribute type="xs:byte" name="expectation" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="check" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="name"/>
                          <xs:element name="question" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="name"/>
                                <xs:element name="answer">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:dateTime" name="given" use="optional"/>
                                        <xs:attribute type="xs:boolean" name="valid" use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:dateTime" name="asked" use="optional"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="class" use="optional"/>
                        <xs:attribute type="xs:dateTime" name="started" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="level" use="optional"/>
                  <xs:attribute type="xs:dateTime" name="recalculated" use="optional"/>
                  <xs:attribute type="xs:byte" name="expectation" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== miroque/pp-model-concept-01/src/test/resources/pp-simple-data.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><personal-profile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="personal-profile.xsd">
	<identity>
		<person>
			<fio>Pan Aleks Vlad</fio>
			<birth-date>1982-03-14</birth-date>
		</person>
		<account>
			<login>miroque</login>
		</account>
	</identity>
	<data>
		<knowledge expectation="30" level="0" recalculated="2020-12-02T12:00:00.123Z">
			<name>data engineer</name>
			<knowledge expectation="10" level="0" recalculated="2020-12-02T12:00:00.123Z">
				<name>apache spark</name>
			</knowledge>
			<knowledge expectation="20" level="0" recalculated="2020-12-02T12:00:00.123Z">
				<name>apache hive</name>
			</knowledge>
		</knowledge>
		<knowledge expectation="30" level="75" recalculated="2022-03-19T12:00:00.123Z">
			<name>java programmer</name>
			<check class="NA" started="2022-03-19T12:00:00.123Z">
				<name>с сайта с тестами прохожу тест</name>
				<question asked="2022-03-19T12:00:00.123Z">
					<name>Что такое класс?</name>
					<answer given="2022-03-19T12:00:00.123Z" valid="true">Это контакт
						описания свойств и поведения
						всех объектов обладающих этими
						свойствами.</answer>
				</question>
			</check>
			<check class="verified center" started="2022-03-19T12:00:00.123Z">
				<name>Официальный сайт</name>
				<question asked="2022-03-19T12:00:00.123Z">
					<name>Что такое класс?</name>
					<answer given="2022-03-19T12:00:00.123Z" valid="true">Это контакт
						описания свойств и поведения
						всех объектов обладающих этими
						свойствами.</answer>
				</question>
			</check>
		</knowledge>
		<knowledge expectation="30" level="75" recalculated="2022-03-19T12:00:00.123Z">
			<name>математика</name>
			<check class="экзамен на неделе" started="2022-03-19T12:00:00.123Z">
				<name>задачи в классе</name>
				<question asked="2022-03-19T12:00:00.123Z">
					<name>сколько будет 4+4?</name>
					<answer given="2022-03-19T12:00:00.123Z" valid="true">8</answer>
				</question>
				<question asked="2022-03-19T12:00:00.123Z">
					<name>сколько будет 5+4?</name>
					<answer given="2022-03-19T12:00:00.123Z" valid="false">20</answer>
				</question>
			</check>
			<check class="verified center" started="2022-03-19T12:00:00.123Z">
				<name>Официальный сайт</name>
				<question asked="2022-03-19T12:00:00.123Z">
					<name>Что такое класс?</name>
					<answer given="2022-03-19T12:00:00.123Z" valid="true">Это контакт
						описания свойств и поведения
						всех объектов обладающих этими
						свойствами.</answer>
				</question>
			</check>
		</knowledge>
<knowledge id="1"><name>Test 0</name></knowledge><knowledge id="2"><name>Test 1</name></knowledge><knowledge id="3"><name>Test 2</name></knowledge><knowledge id="4"><name>Test 3</name></knowledge><knowledge id="5"><name>Test 4</name></knowledge></data>
</personal-profile>

=== miroque/pp-model-concept-01/src/test/resources/pp-miroque.xml
<?xml version="1.0" encoding="UTF-8"?>
<personal-profile
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="personal-profile.xsd">
	<identity>
		<person>
			<fio>Pan Aleks Vlad</fio>
			<birth-date>1982-03-14</birth-date>
		</person>
		<account>
			<login>miroque</login>
		</account>
	</identity>
	<data>
		<knowledge level="0" recalculated="2020-12-02T12:00:00.123Z"
			expectation="30">
			<name>data engineer</name>
			<knowledge level="0"
				recalculated="2020-12-02T12:00:00.123Z" expectation="10">
				<name>apache spark</name>
			</knowledge>
			<knowledge level="0"
				recalculated="2020-12-02T12:00:00.123Z" expectation="20">
				<name>apache hive</name>
			</knowledge>
		</knowledge>
		<knowledge level="75"
			recalculated="2022-03-19T12:00:00.123Z" expectation="30">
			<name>java programmer</name>
			<check class="NA" started="2022-03-19T12:00:00.123Z">
				<name>с сайта с тестами прохожу тест</name>
				<question asked="2022-03-19T12:00:00.123Z">
					<name>Что такое класс?</name>
					<answer given="2022-03-19T12:00:00.123Z" valid="true">Это контакт
						описания свойств и поведения
						всех объектов обладающих этими
						свойствами.</answer>
				</question>
			</check>
			<check class="verified center" started="2022-03-19T12:00:00.123Z">
				<name>Официальный сайт</name>
				<question asked="2022-03-19T12:00:00.123Z">
					<name>Что такое класс?</name>
					<answer given="2022-03-19T12:00:00.123Z" valid="true">Это контакт
						описания свойств и поведения
						всех объектов обладающих этими
						свойствами.</answer>
				</question>
			</check>
		</knowledge>
		<knowledge level="75"
			recalculated="2022-03-19T12:00:00.123Z" expectation="30">
			<name>математика</name>
			<check class="экзамен на неделе" started="2022-03-19T12:00:00.123Z">
				<name>задачи в классе</name>
				<question asked="2022-03-19T12:00:00.123Z">
					<name>сколько будет 4+4?</name>
					<answer given="2022-03-19T12:00:00.123Z" valid="true">8</answer>
				</question>
				<question asked="2022-03-19T12:00:00.123Z">
					<name>сколько будет 5+4?</name>
					<answer given="2022-03-19T12:00:00.123Z" valid="false">20</answer>
				</question>
			</check>
			<check class="verified center" started="2022-03-19T12:00:00.123Z">
				<name>Официальный сайт</name>
				<question asked="2022-03-19T12:00:00.123Z">
					<name>Что такое класс?</name>
					<answer given="2022-03-19T12:00:00.123Z" valid="true">Это контакт
						описания свойств и поведения
						всех объектов обладающих этими
						свойствами.</answer>
				</question>
			</check>
		</knowledge>
	</data>
</personal-profile>
